// Generated by gencpp from file visionprocess/ROI.msg
// DO NOT EDIT!


#ifndef VISIONPROCESS_MESSAGE_ROI_H
#define VISIONPROCESS_MESSAGE_ROI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visionprocess
{
template <class ContainerAllocator>
struct ROI_
{
  typedef ROI_<ContainerAllocator> Type;

  ROI_()
    : x(0)
    , y(0)
    , width(0)
    , height(0)  {
    }
  ROI_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _width_type;
  _width_type width;

   typedef int64_t _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::visionprocess::ROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visionprocess::ROI_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_

typedef ::visionprocess::ROI_<std::allocator<void> > ROI;

typedef boost::shared_ptr< ::visionprocess::ROI > ROIPtr;
typedef boost::shared_ptr< ::visionprocess::ROI const> ROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visionprocess::ROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visionprocess::ROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visionprocess

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'visionprocess': ['/home/wu/rosquadcopter/src/visionprocess/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visionprocess::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visionprocess::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visionprocess::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visionprocess::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visionprocess::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visionprocess::ROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visionprocess::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da3a0b875a11573348524040e5637f14";
  }

  static const char* value(const ::visionprocess::ROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda3a0b875a115733ULL;
  static const uint64_t static_value2 = 0x48524040e5637f14ULL;
};

template<class ContainerAllocator>
struct DataType< ::visionprocess::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visionprocess/ROI";
  }

  static const char* value(const ::visionprocess::ROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visionprocess::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
int64 width\n\
int64 height\n\
";
  }

  static const char* value(const ::visionprocess::ROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visionprocess::ROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visionprocess::ROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visionprocess::ROI_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<int64_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int64_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISIONPROCESS_MESSAGE_ROI_H
